### ISSUE TITLE
Just crashes :(

### ISSUE THREAD

**Issue by loxchmorez** [tien0246/IOS-Il2CppDumper#1]
I compiled it myself for ARM64e devices, but after entering the game and pressing the OK button, after 10 seconds the game crashes without producing any results.
Device:
iPad Air (5th generation)
iOS 15.6.1 with Bootstrap
Critical Ops

https://github.com/user-attachments/assets/5fb9d64b-c6e1-4b64-971e-dde4aaa35d55

**Comment by Batchhh** [comment]
Not all apps are supported!

**Comment by Batchhh** [comment]
We'll implement edited code in the future, for different games that requires manual work

**Comment by loxchmorez** [comment]
Thanks
